title: samit
author: "Samit Mohan"
email: "samitmohan@gmail.com"
description: my home on the internet
baseurl: ""
url: "https://samitmohan.github.io"

theme: minima
future: true
show_excerpts: false

header_pages:
  - projects.markdown
  - search.html

twitter_username: samitmohan
github_username: samitmohan
linkedin_username: samit-mohan


markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  excerpt_only: true

sass:
  style: compressed
